name: todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pedantic_mono: ^1.24.0+1
  shared_preferences: ^2.2.1
  slang: ^3.24.0
  slang_flutter: ^3.24.0
  uuid: ^4.1.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  slang_build_runner: ^3.24.0

flutter:
  uses-material-design: true
